on:
  pull_request:
    branches:
      - '*'
  push:
jobs:
  compile:
    if: ${{ github.event_name == 'pull_request' && github.event.pull_request.draft == false || github.ref_name == 'main' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - shell: bash
        name: build
        run: |
          sudo apt update
          sudo apt install gcc-11
          make
