on:
  pull_request:
    branches:
      - '*'
  push:
jobs:
  compile:
    if: ${{ github.event_name == 'pull_request' && github.event.pull_request.draft == false || github.ref_name == 'main' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - shell: bash
        name: build
        run: |
          sudo apt update
          sudo pip install regex
          sudo apt install -y gcc-11 glibc-static libc6-dev
          python3 ./pack.py
