on:
  pull_request:
    branches:
      - '*'
  push:
jobs:
  compile:
    if: ${{ github.event_name == 'pull_request' && github.event.pull_request.draft == false || github.ref_name == 'main' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - shell: bash
        name: build
        run: |
          sudo apt update
          pip3 install regex
          sudo apt install -y gcc-11 libc6-dev
          python3 ./pack.py
      - uses: actions/upload-artifact
        with:
          name: microworm
          path: bin/microworm