on:
  pull_request:
    branches:
      - '*'
  push:
jobs:
  compile:
    if: ${{ github.event_name == 'pull_request' && github.event.pull_request.draft == false || github.ref_name == 'main' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/cache@v4
        with:
          key: 'key'
          path: '${{ github.workspace }}/cosmocc'

      - shell: bash
        name: install toolchain
        run: |
          sudo wget -O /usr/bin/ape https://cosmo.zip/pub/cosmos/bin/ape-$(uname -m).elf
          sudo chmod +x /usr/bin/ape

      - shell: bash
        if: !hashFiles(format('{0}/cosmocc', github.workspace))
        run: |
          mkdir cosmocc
          cd cosmocc
          wget https://cosmo.zip/pub/cosmocc/cosmocc.zip
          unzip cosmocc.zip

      - shell: bash
        name: build
        run: make all

      - shell: bash
        name: run
        run: ./bin/main.com
