on:
  pull_request:
    branches:
      - '*'
jobs:
  compile:
    if: ${{ github.event_name == 'pull_request' && github.event.pull_request.draft == false }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: aminya/setup-cpp@v0.44.0
      - shell: sh
        run: make all-linux
